import collections
from .helpers import is_non_empty_string as is_non_empty_string
from typing import Any

collectionsAbc = collections.abc
collectionsAbc = collections

class CopyConditions(collectionsAbc.MutableMapping):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...
    def __delitem__(self, key: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def __len__(self): ...
    def set_match_etag(self, etag: Any) -> None: ...
    def set_match_etag_except(self, etag: Any) -> None: ...
    def set_unmodified_since(self, mod_time: Any) -> None: ...
    def set_modified_since(self, mod_time: Any) -> None: ...
