from .error import InvalidArgumentError as InvalidArgumentError, InvalidSizeError as InvalidSizeError
from typing import Any

class SSE_C:
    key: Any = ...
    def __init__(self, key: Any) -> None: ...
    def type(self): ...
    def marshal(self): ...

class copy_SSE_C:
    key: Any = ...
    def __init__(self, key: Any) -> None: ...
    def type(self): ...
    def marshal(self): ...

class SSE_KMS:
    key: Any = ...
    context: Any = ...
    def __init__(self, key: Any, context: Any) -> None: ...
    def type(self): ...
    def marshal(self): ...

class SSE_S3:
    def type(self): ...
    def marshal(self): ...
