from typing import Any

def xml_marshal_bucket_constraint(region: Any): ...
def xml_marshal_select(opts: Any): ...
def xml_marshal_complete_multipart_upload(uploaded_parts: Any): ...
def xml_marshal_bucket_notifications(notifications: Any): ...

NOTIFICATIONS_ARN_FIELDNAME_MAP: Any

def xml_marshal_delete_objects(object_names: Any): ...
