from django.contrib import admin
from rest_framework.authtoken.models import Token as Token
from typing import Any

class TokenAdmin(admin.ModelAdmin):
    list_display: Any = ...
    fields: Any = ...
    ordering: Any = ...
