from django.db import models
from typing import Any

class Token(models.Model):
    key: Any = ...
    user: Any = ...
    created: Any = ...
    class Meta:
        abstract: Any = ...
        verbose_name: Any = ...
        verbose_name_plural: Any = ...
    def save(self, *args: Any, **kwargs: Any): ...
    def generate_key(self): ...
