from rest_framework import serializers as serializers
from typing import Any

class AuthTokenSerializer(serializers.Serializer):
    username: Any = ...
    password: Any = ...
    def validate(self, attrs: Any): ...
