from .formatter import Formatter as Formatter
from .sorted_dict import SortedDict as SortedDict
from typing import Any

def format_line(line: Any): ...

class PrettyDiff:
    pretty: Any = ...
    snapshottest: Any = ...
    obj: Any = ...
    def __init__(self, obj: Any, snapshottest: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def get_diff(self, other: Any): ...
