from .module import SnapshotModule as SnapshotModule
from .unittest import TestCase as uTestCase
from django.test import SimpleTestCase as dSimpleTestCase, TestCase as dTestCase
from django.test.runner import DiscoverRunner
from snapshottest.reporting import reporting_lines as reporting_lines
from typing import Any, Optional

class TestRunner(DiscoverRunner):
    separator1: Any = ...
    separator2: Any = ...
    def __init__(self, snapshot_update: bool = ..., **kwargs: Any) -> None: ...
    @classmethod
    def add_arguments(cls, parser: Any) -> None: ...
    def run_tests(self, test_labels: Any, extra_tests: Optional[Any] = ..., **kwargs: Any): ...
    def print_report(self) -> None: ...

class TestCase(uTestCase, dTestCase): ...
class SimpleTestCase(uTestCase, dSimpleTestCase): ...
