from .formatter import Formatter as Formatter
from .formatters import BaseFormatter as BaseFormatter
from typing import Any

class FileSnapshot:
    path: Any = ...
    def __init__(self, path: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...

class FileSnapshotFormatter(BaseFormatter):
    def can_format(self, value: Any): ...
    def store(self, test: Any, value: Any): ...
    def get_imports(self): ...
    def format(self, value: Any, indent: Any, formatter: Any): ...
    def assert_value_matches_snapshot(self, test: Any, test_value: Any, snapshot_value: Any, formatter: Any) -> None: ...
    @staticmethod
    def get_file_snapshot_dir(test: Any): ...
