from .formatters import default_formatters as default_formatters
from typing import Any, Optional

class Formatter:
    formatters: Any = ...
    htchar: Any = ...
    lfchar: str = ...
    indent: int = ...
    imports: Any = ...
    def __init__(self, imports: Optional[Any] = ...) -> None: ...
    def __call__(self, value: Any, **args: Any): ...
    def format(self, value: Any, indent: Any): ...
    def normalize(self, value: Any): ...
    @staticmethod
    def get_formatter(value: Any): ...
    @staticmethod
    def register_formatter(formatter: Any) -> None: ...
