from typing import Any

class GenericRepr:
    representation: Any = ...
    def __init__(self, representation: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
    @staticmethod
    def from_value(value: Any): ...
