from .module import SnapshotModule as SnapshotModule
from .reporting import reporting_lines as reporting_lines
from .unittest import TestCase as TestCase
from nose.plugins import Plugin
from typing import Any

log: Any

class SnapshotTestPlugin(Plugin):
    name: str = ...
    enabled: bool = ...
    separator1: Any = ...
    separator2: Any = ...
    def options(self, parser: Any, env: Any = ...) -> None: ...
    snapshot_update: Any = ...
    def configure(self, options: Any, conf: Any) -> None: ...
    def wantClass(self, cls: Any) -> None: ...
    def afterContext(self) -> None: ...
    def report(self, stream: Any) -> None: ...
