from .diff import PrettyDiff as PrettyDiff
from .module import SnapshotModule as SnapshotModule, SnapshotTest as SnapshotTest
from .reporting import diff_report as diff_report, reporting_lines as reporting_lines
from typing import Any, Optional

def pytest_addoption(parser: Any) -> None: ...

class PyTestSnapshotTest(SnapshotTest):
    request: Any = ...
    def __init__(self, request: Optional[Any] = ...) -> None: ...
    @property
    def module(self): ...
    @property
    def update(self): ...
    @property
    def test_name(self): ...

class SnapshotSession:
    verbose: Any = ...
    config: Any = ...
    def __init__(self, config: Any) -> None: ...
    def display(self, tr: Any) -> None: ...

def pytest_assertrepr_compare(op: Any, left: Any, right: Any): ...
def snapshot(request: Any) -> None: ...
def pytest_terminal_summary(terminalreporter: Any) -> None: ...
def pytest_configure(config: Any) -> None: ...
