import unittest
from .diff import PrettyDiff as PrettyDiff
from .module import SnapshotModule as SnapshotModule, SnapshotTest as SnapshotTest
from .reporting import diff_report as diff_report
from typing import Any

class UnitTestSnapshotTest(SnapshotTest):
    test_class: Any = ...
    test_id: Any = ...
    test_filepath: Any = ...
    assertEqual: Any = ...
    should_update: Any = ...
    def __init__(self, test_class: Any, test_id: Any, test_filepath: Any, should_update: Any, assertEqual: Any) -> None: ...
    @property
    def module(self): ...
    @property
    def update(self): ...
    def assert_equals(self, value: Any, snapshot: Any) -> None: ...
    @property
    def test_name(self): ...

class TestCase(unittest.TestCase):
    snapshot_should_update: bool = ...
    @classmethod
    def setUpClass(cls): ...
    def comparePrettyDifs(self, obj1: Any, obj2: Any, msg: Any) -> None: ...
    @classmethod
    def tearDownClass(cls) -> None: ...
    def setUp(self) -> None: ...
    def tearDown(self) -> None: ...
    def assert_match_snapshot(self, value: Any, name: str = ...) -> None: ...
    assertMatchSnapshot: Any = ...
