import datetime
from typing import Any

PY2: Any

def is_string(obj: Any): ...
def force_text(text: Any): ...

UTC: Any

class _UTC(datetime.tzinfo):
    def utcoffset(self, dt: Any): ...
    def tzname(self, dt: Any): ...
    def dst(self, dt: Any): ...
    def localize(self, dt: Any) -> None: ...
