from . import base as base, declarations as declarations, errors as errors
from .compat import is_string as is_string
from typing import Any

import_failure = e
logger: Any
DEFAULT_DB_ALIAS: str

def require_django() -> None: ...
def get_model(app: Any, model: Any): ...

class DjangoOptions(base.FactoryOptions):
    model: Any = ...
    def get_model_class(self): ...

class DjangoModelFactory(base.Factory):
    class Meta:
        abstract: bool = ...

class FileField(declarations.ParameteredAttribute):
    DEFAULT_FILENAME: str = ...
    def __init__(self, **defaults: Any) -> None: ...
    def generate(self, step: Any, params: Any): ...

class ImageField(FileField):
    DEFAULT_FILENAME: str = ...

class mute_signals:
    signals: Any = ...
    paused: Any = ...
    def __init__(self, *signals: Any) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type: Any, exc_value: Any, traceback: Any) -> None: ...
    def copy(self): ...
    def __call__(self, callable_obj: Any): ...
