from . import declarations as declarations
from typing import Any, Optional

class Faker(declarations.BaseDeclaration):
    provider: Any = ...
    provider_kwargs: Any = ...
    locale: Any = ...
    def __init__(self, provider: Any, **kwargs: Any) -> None: ...
    def generate(self, extra_kwargs: Optional[Any] = ...): ...
    def evaluate(self, instance: Any, step: Any, extra: Any): ...
    @classmethod
    def override_default_locale(cls, locale: Any) -> None: ...
    @classmethod
    def add_provider(cls, provider: Any, locale: Optional[Any] = ...) -> None: ...
