from . import compat as compat
from typing import Any, Optional

def import_object(module_name: Any, attribute_name: Any): ...

class log_pprint:
    args: Any = ...
    kwargs: Any = ...
    def __init__(self, args: Any = ..., kwargs: Optional[Any] = ...) -> None: ...

def log_repr(obj: Any): ...

class ResetableIterator:
    iterator: Any = ...
    past_elements: Any = ...
    next_elements: Any = ...
    def __init__(self, iterator: Any, **kwargs: Any) -> None: ...
    def __iter__(self) -> Any: ...
    def reset(self) -> None: ...

class OrderedBase:
    CREATION_COUNTER_FIELD: str = ...
    def __init__(self, **kwargs: Any) -> None: ...

def sort_ordered_objects(items: Any, getter: Any = ...): ...
