from ..utils import base64 as base64, is_str as is_str, unbase64 as unbase64
from .connectiontypes import Connection as Connection, Edge as Edge, PageInfo as PageInfo
from typing import Any, Optional

def connection_from_list(data: Any, args: Optional[Any] = ..., **kwargs: Any): ...
def connection_from_promised_list(data_promise: Any, args: Optional[Any] = ..., **kwargs: Any): ...
def connection_from_list_slice(list_slice: Any, args: Optional[Any] = ..., connection_type: Optional[Any] = ..., edge_type: Optional[Any] = ..., pageinfo_type: Optional[Any] = ..., slice_start: int = ..., list_length: int = ..., list_slice_length: Optional[Any] = ...): ...

PREFIX: str

def connection_from_promised_list_slice(data_promise: Any, args: Optional[Any] = ..., **kwargs: Any): ...
def offset_to_cursor(offset: Any): ...
def cursor_to_offset(cursor: Any): ...
def cursor_for_object_in_connection(data: Any, _object: Any): ...
def get_offset_with_default(cursor: Optional[Any] = ..., default_offset: int = ...): ...
