from typing import Any

class Connection:
    edges: Any = ...
    page_info: Any = ...
    def __init__(self, edges: Any, page_info: Any) -> None: ...
    def to_dict(self): ...

class PageInfo:
    startCursor: Any = ...
    endCursor: Any = ...
    hasPreviousPage: Any = ...
    hasNextPage: Any = ...
    def __init__(self, start_cursor: str = ..., end_cursor: str = ..., has_previous_page: bool = ..., has_next_page: bool = ...) -> None: ...
    def to_dict(self): ...

class Edge:
    node: Any = ...
    cursor: Any = ...
    def __init__(self, node: Any, cursor: Any) -> None: ...
    def to_dict(self): ...
