from ..utils.orderedtype import OrderedType as OrderedType
from typing import Any

class UnmountedType(OrderedType):
    args: Any = ...
    kwargs: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get_type(self) -> None: ...
    def mount_as(self, _as: Any): ...
    def Field(self): ...
    def InputField(self): ...
    def Argument(self): ...
    def __eq__(self, other: Any) -> Any: ...
