from . import widgets as widgets
from .fields import LocalizedCharField as LocalizedCharField, LocalizedField as LocalizedField, LocalizedFileField as LocalizedFileField, LocalizedTextField as LocalizedTextField
from typing import Any

FORMFIELD_FOR_LOCALIZED_FIELDS_DEFAULTS: Any

class LocalizedFieldsAdminMixin:
    class Media:
        css: Any = ...
        js: Any = ...
    formfield_overrides: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
