from typing import Any, Optional

class LocalizedValueDescriptor:
    field: Any = ...
    def __init__(self, field: Any) -> None: ...
    def __get__(self, instance: Any, cls: Optional[Any] = ...): ...
    def __set__(self, instance: Any, value: Any) -> None: ...
