from .value import LocalizedFileValue as LocalizedFileValue, LocalizedIntegerValue as LocalizedIntegerValue, LocalizedStringValue as LocalizedStringValue, LocalizedValue as LocalizedValue
from .widgets import AdminLocalizedIntegerFieldWidget as AdminLocalizedIntegerFieldWidget, LocalizedCharFieldWidget as LocalizedCharFieldWidget, LocalizedFieldWidget as LocalizedFieldWidget, LocalizedFileWidget as LocalizedFileWidget
from django import forms
from typing import Any, List, Optional, Union

class LocalizedFieldForm(forms.MultiValueField):
    widget: Any = ...
    field_class: Any = ...
    value_class: Any = ...
    def __init__(self, *args: Any, required: Union[bool, List[str]]=..., **kwargs: Any) -> Any: ...
    def compress(self, value: List[str]) -> value_class: ...

class LocalizedCharFieldForm(LocalizedFieldForm):
    widget: Any = ...
    value_class: Any = ...

class LocalizedTextFieldForm(LocalizedFieldForm):
    value_class: Any = ...

class LocalizedIntegerFieldForm(LocalizedFieldForm):
    widget: Any = ...
    value_class: Any = ...

class LocalizedFileFieldForm(LocalizedFieldForm, forms.FileField):
    widget: Any = ...
    field_class: Any = ...
    value_class: Any = ...
    def clean(self, value: Any, initial: Optional[Any] = ...): ...
    def bound_data(self, data: Any, initial: Any): ...
