from .value import LocalizedValue as LocalizedValue
from django import forms
from typing import Any, List

class LocalizedFieldWidget(forms.MultiWidget):
    template_name: str = ...
    widget: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def decompress(self, value: LocalizedValue) -> List[str]: ...
    def get_context(self, name: Any, value: Any, attrs: Any): ...
    @staticmethod
    def build_widget_attrs(widget: Any, value: Any, attrs: Any): ...

class LocalizedCharFieldWidget(LocalizedFieldWidget):
    widget: Any = ...

class LocalizedFileWidget(LocalizedFieldWidget):
    widget: Any = ...

class AdminLocalizedFieldWidget(LocalizedFieldWidget):
    template_name: str = ...
    widget: Any = ...

class AdminLocalizedCharFieldWidget(AdminLocalizedFieldWidget):
    widget: Any = ...

class AdminLocalizedFileFieldWidget(AdminLocalizedFieldWidget):
    widget: Any = ...

class AdminLocalizedIntegerFieldWidget(AdminLocalizedFieldWidget):
    widget: Any = ...
