from django.core.management.base import BaseCommand
from rest_framework import renderers as renderers
from rest_framework.schemas import coreapi as coreapi
from rest_framework.schemas.openapi import SchemaGenerator as SchemaGenerator
from typing import Any

OPENAPI_MODE: str
COREAPI_MODE: str

class Command(BaseCommand):
    help: str = ...
    def get_mode(self): ...
    def add_arguments(self, parser: Any) -> None: ...
    def handle(self, *args: Any, **options: Any) -> None: ...
    def get_renderer(self, format: Any): ...
    def get_generator_class(self): ...
