from graphene import ObjectType
from typing import Any

class DjangoDebugSQL(ObjectType):
    class Meta:
        description: str = ...
    vendor: Any = ...
    alias: Any = ...
    sql: Any = ...
    duration: Any = ...
    raw_sql: Any = ...
    params: Any = ...
    start_time: Any = ...
    stop_time: Any = ...
    is_slow: Any = ...
    is_select: Any = ...
    trans_id: Any = ...
    trans_status: Any = ...
    iso_level: Any = ...
    encoding: Any = ...
