from ..util import resolve_object_property as resolve_object_property
from ..value import LocalizedValue as LocalizedValue
from .field import LocalizedField as LocalizedField
from typing import Any

class LocalizedAutoSlugField(LocalizedField):
    populate_from: Any = ...
    include_time: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def deconstruct(self): ...
    def formfield(self, **kwargs: Any): ...
    def pre_save(self, instance: Any, add: bool) -> Any: ...
