from ..forms import LocalizedIntegerFieldForm as LocalizedIntegerFieldForm
from ..value import LocalizedIntegerValue as LocalizedIntegerValue, LocalizedValue as LocalizedValue
from .field import LocalizedField as LocalizedField
from typing import Any, Dict, Optional, Union

class LocalizedIntegerField(LocalizedField):
    attr_class: Any = ...
    @classmethod
    def from_db_value(cls: Any, value: Any, *_: Any) -> Optional[LocalizedIntegerValue]: ...
    def to_python(self, value: Union[Dict[str, int], int, None]) -> LocalizedIntegerValue: ...
    def get_prep_value(self, value: LocalizedIntegerValue) -> dict: ...
    def formfield(self, **kwargs: Any): ...
