from .errors import SelectCRCValidationError as SelectCRCValidationError, SelectMessageError as SelectMessageError
from .helpers import ERROR as ERROR, EVENT as EVENT, EVENT_CONT as EVENT_CONT, EVENT_CONTENT_TYPE as EVENT_CONTENT_TYPE, EVENT_END as EVENT_END, EVENT_PROGRESS as EVENT_PROGRESS, EVENT_RECORDS as EVENT_RECORDS, EVENT_STATS as EVENT_STATS, byte_int as byte_int, calculate_crc as calculate_crc, validate_crc as validate_crc
from binascii import crc32 as crc32
from typing import Any
from xml.etree.cElementTree import ParseError as ParseError

class SelectObjectReader:
    response: Any = ...
    remaining_bytes: Any = ...
    stat: Any = ...
    prog: Any = ...
    def __init__(self, response: Any) -> None: ...
    def readable(self): ...
    def writeable(self): ...
    def close(self) -> None: ...
    def stats(self): ...
    def progress(self): ...
    def stream(self, num_bytes: Any = ...) -> None: ...
