from .hstore_required import HStoreRequiredSchemaEditorMixin as HStoreRequiredSchemaEditorMixin
from .hstore_unique import HStoreUniqueSchemaEditorMixin as HStoreUniqueSchemaEditorMixin
from typing import Any

logger: Any

class SchemaEditor:
    post_processing_mixins: Any = ...
    base: Any = ...
    def __init__(self, connection: Any, collect_sql: bool = ..., atomic: bool = ...) -> None: ...
    def create_model(self, model: Any) -> None: ...
    def delete_model(self, model: Any) -> None: ...
    def alter_db_table(self, model: Any, old_db_table: Any, new_db_table: Any) -> None: ...
    def add_field(self, model: Any, field: Any) -> None: ...
    def remove_field(self, model: Any, field: Any) -> None: ...
    def alter_field(self, model: Any, old_field: Any, new_field: Any, strict: bool = ...) -> None: ...

class DatabaseWrapper:
    SchemaEditorClass: Any = ...
    def prepare_database(self) -> None: ...
