from ..fields import HStoreField as HStoreField
from typing import Any

class HStoreUniqueSchemaEditorMixin:
    sql_hstore_unique_create: str = ...
    sql_hstore_unique_rename: str = ...
    sql_hstore_unique_drop: str = ...
    def create_model(self, model: Any) -> None: ...
    def delete_model(self, model: Any) -> None: ...
    def alter_db_table(self, model: Any, old_db_table: Any, new_db_table: Any) -> None: ...
    def add_field(self, model: Any, field: Any) -> None: ...
    def remove_field(self, model: Any, field: Any) -> None: ...
    def alter_field(self, model: Any, old_field: Any, new_field: Any, strict: bool = ...) -> None: ...
