from ..utils import base64 as base64, unbase64 as unbase64
from typing import Any, Optional

def node_definitions(id_fetcher: Any, type_resolver: Optional[Any] = ..., id_resolver: Optional[Any] = ...): ...
def to_global_id(type: Any, id: Any): ...
def from_global_id(global_id: Any): ...
def global_id_field(type_name: Any, id_fetcher: Optional[Any] = ...): ...
