from django.db.models.sql.compiler import SQLInsertCompiler, SQLUpdateCompiler
from psqlextra.expressions import HStoreValue as HStoreValue
from typing import Any

class PostgresReturningUpdateCompiler(SQLUpdateCompiler):
    def execute_sql(self, _result_type: Any): ...
    def as_sql(self): ...

class PostgresInsertCompiler(SQLInsertCompiler):
    qn: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def as_sql(self, return_id: bool = ...): ...
    def execute_sql(self, return_id: bool = ...): ...
