from django.db.models.sql.datastructures import Join
from typing import Any, List, Tuple

class ConditionalJoin(Join):
    join_type: str = ...
    extra_conditions: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def add_condition(self, field: Any, value: Any) -> None: ...
    def as_sql(self, compiler: Any, connection: Any) -> Tuple[str, List[Any]]: ...
    @classmethod
    def from_join(cls: Any, join: Join) -> ConditionalJoin: ...
