from .datastructures import ConditionalJoin as ConditionalJoin
from .expressions import HStoreColumn as HStoreColumn
from .fields import HStoreField as HStoreField
from django.db import models as models
from django.db.models import sql
from enum import Enum
from typing import Any, Dict, List

class ConflictAction(Enum):
    NOTHING: str = ...
    UPDATE: str = ...

class PostgresQuery(sql.Query):
    def rename_annotations(self, annotations: Any) -> None: ...
    def add_join_conditions(self, conditions: Dict[str, Any]) -> None: ...
    def add_fields(self, field_names: List[str], allow_m2m: bool=...) -> bool: ...

class PostgresInsertQuery(sql.InsertQuery):
    conflict_target: Any = ...
    conflict_action: Any = ...
    update_fields: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def values(self, objs: List, insert_fields: List, update_fields: List=...) -> Any: ...
