from ..utils import import_single_dispatch as import_single_dispatch
from .forms import GlobalIDFormField as GlobalIDFormField, GlobalIDMultipleChoiceField as GlobalIDMultipleChoiceField
from typing import Any

singledispatch: Any

def convert_form_field(field: Any) -> None: ...
def convert_form_field_to_string(field: Any): ...
def convert_form_field_to_uuid(field: Any): ...
def convert_form_field_to_int(field: Any): ...
def convert_form_field_to_boolean(field: Any): ...
def convert_form_field_to_nullboolean(field: Any): ...
def convert_form_field_to_float(field: Any): ...
def convert_form_field_to_list(field: Any): ...
def convert_form_field_to_date(field: Any): ...
def convert_form_field_to_datetime(field: Any): ...
def convert_form_field_to_time(field: Any): ...
def convert_form_field_to_id(field: Any): ...
