from django.forms import Field, MultipleChoiceField
from typing import Any

class GlobalIDFormField(Field):
    default_error_messages: Any = ...
    def clean(self, value: Any): ...

class GlobalIDMultipleChoiceField(MultipleChoiceField):
    default_error_messages: Any = ...
    def valid_value(self, value: Any): ...
