from django.db import models
from typing import Any

class MyFakeModel(models.Model):
    cool_name: Any = ...
    created: Any = ...

class MyFakeModelWithPassword(models.Model):
    cool_name: Any = ...
    password: Any = ...
