from rest_framework.views import APIView as APIView
from typing import Any, Optional

def api_view(http_method_names: Optional[Any] = ...): ...
def renderer_classes(renderer_classes: Any): ...
def parser_classes(parser_classes: Any): ...
def authentication_classes(authentication_classes: Any): ...
def throttle_classes(throttle_classes: Any): ...
def permission_classes(permission_classes: Any): ...
def schema(view_inspector: Any): ...
def action(methods: Optional[Any] = ..., detail: Optional[Any] = ..., url_path: Optional[Any] = ..., url_name: Optional[Any] = ..., **kwargs: Any): ...

class MethodMapper(dict):
    action: Any = ...
    def __init__(self, action: Any, methods: Any) -> None: ...
    def get(self, func: Any): ...
    def post(self, func: Any): ...
    def put(self, func: Any): ...
    def patch(self, func: Any): ...
    def delete(self, func: Any): ...
    def head(self, func: Any): ...
    def options(self, func: Any): ...
    def trace(self, func: Any): ...
