from rest_framework.renderers import CoreJSONRenderer as CoreJSONRenderer, DocumentationRenderer as DocumentationRenderer, SchemaJSRenderer as SchemaJSRenderer
from rest_framework.schemas import SchemaGenerator as SchemaGenerator, get_schema_view as get_schema_view
from rest_framework.settings import api_settings as api_settings
from typing import Any, Optional

def get_docs_view(title: Optional[Any] = ..., description: Optional[Any] = ..., schema_url: Optional[Any] = ..., urlconf: Optional[Any] = ..., public: bool = ..., patterns: Optional[Any] = ..., generator_class: Any = ..., authentication_classes: Any = ..., permission_classes: Any = ..., renderer_classes: Optional[Any] = ...): ...
def get_schemajs_view(title: Optional[Any] = ..., description: Optional[Any] = ..., schema_url: Optional[Any] = ..., urlconf: Optional[Any] = ..., public: bool = ..., patterns: Optional[Any] = ..., generator_class: Any = ..., authentication_classes: Any = ..., permission_classes: Any = ...): ...
def include_docs_urls(title: Optional[Any] = ..., description: Optional[Any] = ..., schema_url: Optional[Any] = ..., urlconf: Optional[Any] = ..., public: bool = ..., patterns: Optional[Any] = ..., generator_class: Any = ..., authentication_classes: Any = ..., permission_classes: Any = ..., renderer_classes: Optional[Any] = ...): ...
