from rest_framework import exceptions as exceptions, serializers as serializers
from rest_framework.request import clone_request as clone_request
from rest_framework.utils.field_mapping import ClassLookupDict as ClassLookupDict
from typing import Any

class BaseMetadata:
    def determine_metadata(self, request: Any, view: Any) -> None: ...

class SimpleMetadata(BaseMetadata):
    label_lookup: Any = ...
    def determine_metadata(self, request: Any, view: Any): ...
    def determine_actions(self, request: Any, view: Any): ...
    def get_serializer_info(self, serializer: Any): ...
    def get_field_info(self, field: Any): ...
