from rest_framework import status as status
from rest_framework.response import Response as Response
from rest_framework.settings import api_settings as api_settings
from typing import Any

class CreateModelMixin:
    def create(self, request: Any, *args: Any, **kwargs: Any): ...
    def perform_create(self, serializer: Any) -> None: ...
    def get_success_headers(self, data: Any): ...

class ListModelMixin:
    def list(self, request: Any, *args: Any, **kwargs: Any): ...

class RetrieveModelMixin:
    def retrieve(self, request: Any, *args: Any, **kwargs: Any): ...

class UpdateModelMixin:
    def update(self, request: Any, *args: Any, **kwargs: Any): ...
    def perform_update(self, serializer: Any) -> None: ...
    def partial_update(self, request: Any, *args: Any, **kwargs: Any): ...

class DestroyModelMixin:
    def destroy(self, request: Any, *args: Any, **kwargs: Any): ...
    def perform_destroy(self, instance: Any) -> None: ...
