from django.template.response import SimpleTemplateResponse
from rest_framework.serializers import Serializer as Serializer
from typing import Any, Optional

class Response(SimpleTemplateResponse):
    data: Any = ...
    template_name: Any = ...
    exception: Any = ...
    content_type: Any = ...
    def __init__(self, data: Optional[Any] = ..., status: Optional[Any] = ..., template_name: Optional[Any] = ..., headers: Optional[Any] = ..., exception: bool = ..., content_type: Optional[Any] = ...) -> None: ...
    @property
    def rendered_content(self): ...
    @property
    def status_text(self): ...
