from rest_framework import ISO_8601 as ISO_8601
from typing import Any, Optional

DEFAULTS: Any
IMPORT_STRINGS: Any
REMOVED_SETTINGS: Any

def perform_import(val: Any, setting_name: Any): ...
def import_from_string(val: Any, setting_name: Any): ...

class APISettings:
    defaults: Any = ...
    import_strings: Any = ...
    def __init__(self, user_settings: Optional[Any] = ..., defaults: Optional[Any] = ..., import_strings: Optional[Any] = ...) -> None: ...
    @property
    def user_settings(self): ...
    def __getattr__(self, attr: Any): ...
    def reload(self) -> None: ...

api_settings: Any

def reload_api_settings(*args: Any, **kwargs: Any) -> None: ...
