from .. import BaseProvider as BaseProvider
from typing import Any

localized: bool

class Provider(BaseProvider):
    def boolean(self, chance_of_getting_true: int = ...): ...
    def null_boolean(self): ...
    def binary(self, length: Any = ...): ...
    def md5(self, raw_output: bool = ...): ...
    def sha1(self, raw_output: bool = ...): ...
    def sha256(self, raw_output: bool = ...): ...
    def uuid4(self, cast_to: Any = ...): ...
    def password(self, length: int = ..., special_chars: bool = ..., digits: bool = ..., upper_case: bool = ..., lower_case: bool = ...): ...
