from .sql.tracking import unwrap_cursor as unwrap_cursor, wrap_cursor as wrap_cursor
from .types import DjangoDebug as DjangoDebug
from typing import Any

class DjangoDebugContext:
    debug_promise: Any = ...
    promises: Any = ...
    object: Any = ...
    def __init__(self) -> None: ...
    def get_debug_promise(self): ...
    def on_resolve_all_promises(self, values: Any): ...
    def add_promise(self, promise: Any) -> None: ...
    def enable_instrumentation(self) -> None: ...
    def disable_instrumentation(self) -> None: ...

class DjangoDebugMiddleware:
    def resolve(self, next: Any, root: Any, info: Any, **args: Any): ...
