from rest_framework.settings import api_settings as api_settings
from typing import Any

class ViewInspector:
    instance_schemas: Any = ...
    def __init__(self) -> None: ...
    def __get__(self, instance: Any, owner: Any): ...
    def __set__(self, instance: Any, other: Any) -> None: ...
    @property
    def view(self): ...
    @view.setter
    def view(self, value: Any) -> None: ...
    def view(self) -> None: ...

class DefaultSchema(ViewInspector):
    def __get__(self, instance: Any, owner: Any): ...
