from .generators import BaseSchemaGenerator as BaseSchemaGenerator
from .inspectors import ViewInspector as ViewInspector
from .utils import get_pk_description as get_pk_description, is_list_view as is_list_view
from rest_framework import exceptions as exceptions, serializers as serializers
from rest_framework.compat import uritemplate as uritemplate
from rest_framework.fields import empty as empty
from typing import Any, Optional

class SchemaGenerator(BaseSchemaGenerator):
    def get_info(self): ...
    def get_paths(self, request: Optional[Any] = ...): ...
    def get_schema(self, request: Optional[Any] = ..., public: bool = ...): ...

class AutoSchema(ViewInspector):
    content_types: Any = ...
    method_mapping: Any = ...
    def get_operation(self, path: Any, method: Any): ...
