from rest_framework.mixins import RetrieveModelMixin as RetrieveModelMixin
from typing import Any

def is_list_view(path: Any, method: Any, view: Any): ...
def get_pk_description(model: Any, model_field: Any): ...
