from rest_framework import exceptions as exceptions, renderers as renderers
from rest_framework.response import Response as Response
from rest_framework.schemas import coreapi as coreapi
from rest_framework.settings import api_settings as api_settings
from rest_framework.views import APIView as APIView
from typing import Any

class SchemaView(APIView):
    schema: Any = ...
    renderer_classes: Any = ...
    schema_generator: Any = ...
    public: bool = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def get(self, request: Any, *args: Any, **kwargs: Any): ...
    def handle_exception(self, exc: Any): ...
