from typing import Any, Optional

DOCS_ROOT: Any

def write(fh: Any, s: Any): ...
def write_base_provider(fh: Any, doc: Any, base_provider: Any) -> None: ...
def write_provider(fh: Any, doc: Any, provider: Any, formatters: Any, excludes: Optional[Any] = ...) -> None: ...
def write_docs(*args: Any, **kwargs: Any) -> None: ...
def setup(app: Any) -> None: ...
