from typing import Any

class getargspec:
    argspec: Any = ...
    def __init__(self, method: Any) -> None: ...
    @property
    def args(self): ...
    @property
    def varargs(self): ...
    @property
    def varkw(self): ...
    @property
    def defaults(self): ...
