from typing import Any, Optional

random: Any
mod_random = random

class Generator:
    providers: Any = ...
    def __init__(self, **config: Any) -> None: ...
    def add_provider(self, provider: Any) -> None: ...
    def provider(self, name: Any): ...
    def get_providers(self): ...
    @property
    def random(self): ...
    @random.setter
    def random(self, value: Any) -> None: ...
    def seed_instance(self, seed: Optional[Any] = ...): ...
    @classmethod
    def seed(cls, seed: Optional[Any] = ...) -> None: ...
    def format(self, formatter: Any, *args: Any, **kwargs: Any): ...
    def get_formatter(self, formatter: Any): ...
    def set_formatter(self, name: Any, method: Any) -> None: ...
    def parse(self, text: Any): ...
