from typing import Any

class JEXLAnalyzer:
    config: Any = ...
    def __init__(self, jexl_config: Any) -> None: ...
    def visit(self, expression: Any): ...
    def generic_visit(self, expression: Any) -> None: ...

class ValidatingAnalyzer(JEXLAnalyzer):
    def visit_Transform(self, transform: Any) -> None: ...
    def generic_visit(self, expression: Any) -> None: ...
