class JEXLException(Exception): ...
class ParseError(JEXLException): ...
class InvalidOperatorError(ParseError): ...
class EvaluationError(JEXLException): ...
class MissingTransformError(EvaluationError): ...
