from typing import Any

class Operator:
    symbol: Any = ...
    precedence: Any = ...
    evaluate: Any = ...
    def __init__(self, symbol: Any, precedence: Any, evaluate: Any) -> None: ...

default_binary_operators: Any
default_unary_operators: Any
