from .. import BaseProvider as BaseProvider
from typing import Any

localized: bool

class Provider(BaseProvider):
    formats: Any = ...
    msisdn_formats: Any = ...
    def phone_number(self): ...
    def msisdn(self): ...
