from django.contrib.postgres.fields import HStoreField as DjangoHStoreField
from typing import Any, List, Tuple, Union

class HStoreField(DjangoHStoreField):
    uniqueness: Any = ...
    required: Any = ...
    def __init__(self, *args: Any, uniqueness: List[Union[str, Tuple[str, ...]]]=..., required: List[str]=..., **kwargs: Any) -> Any: ...
    def get_prep_value(self, value: Any): ...
    def deconstruct(self): ...
