from rest_framework.compat import postgres_fields as postgres_fields
from rest_framework.validators import UniqueValidator as UniqueValidator
from typing import Any

NUMERIC_FIELD_TYPES: Any

class ClassLookupDict:
    mapping: Any = ...
    def __init__(self, mapping: Any) -> None: ...
    def __getitem__(self, key: Any): ...
    def __setitem__(self, key: Any, value: Any) -> None: ...

def needs_label(model_field: Any, field_name: Any): ...
def get_detail_view_name(model: Any): ...
def get_field_kwargs(field_name: Any, model_field: Any): ...
def get_relation_kwargs(field_name: Any, relation_info: Any): ...
def get_nested_relation_kwargs(relation_info: Any): ...
def get_url_kwargs(model_field: Any): ...
