from rest_framework.compat import apply_markdown as apply_markdown
from typing import Any

def remove_trailing_string(content: Any, trailing: Any): ...
def dedent(content: Any): ...
def camelcase_to_spaces(content: Any): ...
def markup_description(description: Any): ...

class lazy_format:
    result: Any = ...
    format_string: Any = ...
    args: Any = ...
    kwargs: Any = ...
    def __init__(self, format_string: Any, *args: Any, **kwargs: Any) -> None: ...
    def __mod__(self, value: Any): ...
