from rest_framework import ISO_8601 as ISO_8601
from typing import Any

def datetime_formats(formats: Any): ...
def date_formats(formats: Any): ...
def time_formats(formats: Any): ...
def humanize_strptime(format_string: Any): ...
