from typing import Any

DJANGO_FILTER_INSTALLED: bool

def isiterable(value: Any): ...
def camelize(data: Any): ...
def get_reverse_fields(model: Any, local_field_names: Any) -> None: ...
def maybe_queryset(value: Any): ...
def get_model_fields(model: Any): ...
def is_valid_django_model(model: Any): ...
def import_single_dispatch(): ...
