from .. import Provider as CompanyProvider
from faker.utils.datetime_safe import datetime as datetime
from typing import Any

def calculate_checksum(value: Any): ...

class Provider(CompanyProvider):
    formats: Any = ...
    company_prefixes: Any = ...
    def company_prefix(self): ...
    def businesses_inn(self): ...
    def individuals_inn(self): ...
    def businesses_ogrn(self): ...
    def individuals_ogrn(self): ...
    def kpp(self): ...
