from typing import Any

class Registry:
    def __init__(self) -> None: ...
    def register(self, cls: Any) -> None: ...
    def get_type_for_model(self, model: Any): ...
    def register_converted_field(self, field: Any, converted: Any) -> None: ...
    def get_converted_field(self, field: Any): ...

registry: Any

def get_global_registry(): ...
def reset_global_registry() -> None: ...
