from typing import Any, Optional

DEFAULTS: Any
IMPORT_STRINGS: Any

def perform_import(val: Any, setting_name: Any): ...
def import_from_string(val: Any, setting_name: Any): ...

class GrapheneSettings:
    defaults: Any = ...
    import_strings: Any = ...
    def __init__(self, user_settings: Optional[Any] = ..., defaults: Optional[Any] = ..., import_strings: Optional[Any] = ...) -> None: ...
    @property
    def user_settings(self): ...
    def __getattr__(self, attr: Any): ...

graphene_settings: Any

def reload_graphene_settings(*args: Any, **kwargs: Any) -> None: ...
