from django.db.models.indexes import Index
from typing import Any

class ConditionalUniqueIndex(Index):
    sql_create_index: str = ...
    condition: Any = ...
    def __init__(self, condition: str, fields: Any=..., name: Any=...) -> Any: ...
    def create_sql(self, model: Any, schema_editor: Any, using: str = ...): ...
    def deconstruct(self): ...
