from django.core.management.base import BaseCommand
from graphene_django.settings import graphene_settings as graphene_settings
from typing import Any

class CommandArguments(BaseCommand):
    def add_arguments(self, parser: Any) -> None: ...

class Command(CommandArguments):
    help: str = ...
    can_import_settings: bool = ...
    def save_file(self, out: Any, schema_dict: Any, indent: Any) -> None: ...
    def get_schema(self, schema: Any, out: Any, indent: Any): ...
    def handle(self, *args: Any, **options: Any) -> None: ...
