from ..forms import GlobalIDFormField as GlobalIDFormField, GlobalIDMultipleChoiceField as GlobalIDMultipleChoiceField
from django_filters import Filter, MultipleChoiceFilter
from django_filters.filterset import BaseFilterSet
from typing import Any

class GlobalIDFilter(Filter):
    field_class: Any = ...
    def filter(self, qs: Any, value: Any): ...

class GlobalIDMultipleChoiceFilter(MultipleChoiceFilter):
    field_class: Any = ...
    def filter(self, qs: Any, value: Any): ...

GRAPHENE_FILTER_SET_OVERRIDES: Any

class GrapheneFilterSetMixin(BaseFilterSet):
    FILTER_DEFAULTS: Any = ...

class GrapheneFilterSetMixinPython2(GrapheneFilterSetMixin):
    @classmethod
    def filter_for_reverse_field(cls, f: Any, name: Any): ...
GrapheneFilterSetMixin = GrapheneFilterSetMixinPython2

def setup_filterset(filterset_class: Any): ...
def custom_filterset_factory(model: Any, filterset_base_class: Any = ..., **meta: Any): ...
