from .filterset import custom_filterset_factory as custom_filterset_factory, setup_filterset as setup_filterset
from typing import Any

def get_filtering_args_from_filterset(filterset_class: Any, type: Any): ...
def get_filterset_class(filterset_class: Any, **meta: Any): ...
